### PR TITLE
UAVCAN ⇔ ROS mapping node

### PR DESCRIPTION
**Pull request by jo12bar**
This adds a (mostly stable) node to map UAVCAN messages to ROS messages, and vice versa. It uses [canros](https://github.com/MonashUAS/canros) to send off and receive UAVCAN messages and adds a couple of utility functions based on it to make mapping between the message formats even easier. I've tried to structure everything so that it's easy for anyone to come in and quickly add a new mapping without having to understand exactly how canros or the utility functions work - as in, you should never have to read their source code. As to that end, I've tried to document everything as well as I can, but the documentation may still need to be improved someday. All of the current mappings have been tested to work well inside a VM - I need some hardware hooked up to the TX2 to test things there.

### CODE REVIEW

**Comment by davidlenfesty** [comment]
The original issue was that hardware_interface was not included in the build process at all.

Now, hardware_interface depends on the drive controls, which are in station2.

I'm going to discuss the current state of the repositories with @rpshukla and @kylehennig before I attempt to resolve the current issue and merge this pull request. Other than that everything looks good

**Comment by jo12bar** [comment]
Also, it doesn't seem like the Travis job is actually running our unpack.sh script - it's just using the default entry point that the kinetic-robot docker container provides. So it might not just be the hardware_interface package that's not getting linked in; it might be all of them.

**Comment by jo12bar** [comment]
Actually, ignore my last comment. Travis totally is running unpack.sh - I wasn't sure what this line:
https://github.com/UofA-SPEAR/rover2/blob/b4e27720b07d9a8d3bb5ef03dbdb4e93b509e3af/spear-env.Dockerfile#L16
...actually did. Took me firing up Docker for myself to figure out that it's just setting up some environment variables, and then running whatever command it's given.

In other news, I fixed one bug within `unpack.sh` where I tried to install all the git submodules outside of the actual repository. Now the only error blocking the build from working is that dependency of hardware_interface on drive_controls.

**Review by davidlenfesty — COMMENTED** [review]
👍

**Review by davidlenfesty — APPROVED** [review]
👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍

**Pull request merged**
